#!/usr/bin/env bash

# bash completion for multirust

__multirust_generate_completion()
{
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "$1" -- "$current_word"))
  return 0
}

__multirust_toolchains ()
{
  TOOLCHAINS='stable beta nightly'

  __multirust_generate_completion "$TOOLCHAINS"
}

__multirust_toolchains_installed ()
{
  echo "Checking local override"
  multirust show-override
}


__multirust ()
{
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD-1]}"

  COMMANDS='\override remove-override show-override run update help defaultu \n
            \o-v      r-o             s-o           ru  up     he   de '

  case "$previous_word" in
  run|ru|update|up|override|ov|default|de)    __multirust_toolchains ;;
  remove-override|r-o)                        __multirust_toolchains_installed;;
  *|help|he)                                  __multirust_generate_completion "$COMMANDS" ;;
  esac

  return 0
}

# ZHS shell use bashcompinit instead
if [[ -n ${ZSH_VERSION-} ]]; then
	autoload -U +X bashcompinit && bashcompinit
fi

complete -o default -o nospace -F __multirust multirust